# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frameLogin = QtWidgets.QFrame(self.centralwidget)
        self.frameLogin.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.frameLogin.setStyleSheet("background-color:white;")
        self.frameLogin.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameLogin.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameLogin.setObjectName("frameLogin")
        self.titleLabel = QtWidgets.QLabel(self.frameLogin)
        self.titleLabel.setGeometry(QtCore.QRect(250, 270, 300, 40))
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.logoLabel = QtWidgets.QLabel(self.frameLogin)
        self.logoLabel.setGeometry(QtCore.QRect(300, 100, 200, 150))
        self.logoLabel.setText("")
        self.logoLabel.setPixmap(QtGui.QPixmap("obuvn/images/Icon.png"))
        self.logoLabel.setScaledContents(True)
        self.logoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.logoLabel.setObjectName("logoLabel")
        self.loginLabel = QtWidgets.QLabel(self.frameLogin)
        self.loginLabel.setGeometry(QtCore.QRect(250, 330, 80, 30))
        self.loginLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.loginLabel.setObjectName("loginLabel")
        self.passwordLabel = QtWidgets.QLabel(self.frameLogin)
        self.passwordLabel.setGeometry(QtCore.QRect(250, 370, 80, 30))
        self.passwordLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.passwordLabel.setObjectName("passwordLabel")
        self.loginButton = QtWidgets.QPushButton(self.frameLogin)
        self.loginButton.setGeometry(QtCore.QRect(250, 430, 120, 40))
        self.loginButton.setObjectName("loginButton")
        self.guestButton = QtWidgets.QPushButton(self.frameLogin)
        self.guestButton.setGeometry(QtCore.QRect(380, 430, 160, 40))
        self.guestButton.setObjectName("guestButton")
        self.exitButton = QtWidgets.QPushButton(self.frameLogin)
        self.exitButton.setGeometry(QtCore.QRect(700, 10, 87, 26))
        self.exitButton.setObjectName("exitButton")
        self.loginEdit = QtWidgets.QLineEdit(self.frameLogin)
        self.loginEdit.setGeometry(QtCore.QRect(340, 330, 80, 30))
        self.loginEdit.setObjectName("loginEdit")
        self.passwordEdit = QtWidgets.QLineEdit(self.frameLogin)
        self.passwordEdit.setGeometry(QtCore.QRect(340, 370, 80, 30))
        self.passwordEdit.setObjectName("passwordEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Авторизация ООО \"Обувь\""))
        self.titleLabel.setText(_translate("MainWindow", "ООО \"Обувь\""))
        self.loginLabel.setText(_translate("MainWindow", "Логин"))
        self.passwordLabel.setText(_translate("MainWindow", "Пароль:"))
        self.loginButton.setText(_translate("MainWindow", "Войти"))
        self.guestButton.setText(_translate("MainWindow", "Войти как гость"))
        self.exitButton.setText(_translate("MainWindow", "Выход"))
