# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'product_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProductWindow(object):
    def setupUi(self, ProductWindow):
        ProductWindow.setObjectName("ProductWindow")
        ProductWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(ProductWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.order_button = QtWidgets.QPushButton(self.centralwidget)
        self.order_button.setGeometry(QtCore.QRect(20, 120, 87, 26))
        self.order_button.setObjectName("order_button")
        self.add_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_button.setGeometry(QtCore.QRect(126, 120, 111, 26))
        self.add_button.setObjectName("add_button")
        self.search_label = QtWidgets.QLabel(self.centralwidget)
        self.search_label.setGeometry(QtCore.QRect(20, 160, 66, 18))
        self.search_label.setObjectName("search_label")
        self.search_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.search_edit.setGeometry(QtCore.QRect(100, 160, 113, 26))
        self.search_edit.setObjectName("search_edit")
        self.sort_label = QtWidgets.QLabel(self.centralwidget)
        self.sort_label.setGeometry(QtCore.QRect(230, 160, 101, 18))
        self.sort_label.setObjectName("sort_label")
        self.sort_combo = QtWidgets.QComboBox(self.centralwidget)
        self.sort_combo.setGeometry(QtCore.QRect(340, 160, 79, 26))
        self.sort_combo.setObjectName("sort_combo")
        self.user_label = QtWidgets.QLabel(self.centralwidget)
        self.user_label.setGeometry(QtCore.QRect(535, 10, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setBold(True)
        self.user_label.setFont(font)
        self.user_label.setObjectName("user_label")
        self.logout_button = QtWidgets.QPushButton(self.centralwidget)
        self.logout_button.setGeometry(QtCore.QRect(700, 10, 87, 26))
        self.logout_button.setObjectName("logout_button")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(19, 229, 761, 321))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.products_container = QtWidgets.QWidget()
        self.products_container.setGeometry(QtCore.QRect(0, 0, 759, 319))
        self.products_container.setObjectName("products_container")
        self.scrollArea.setWidget(self.products_container)
        ProductWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ProductWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        ProductWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ProductWindow)
        self.statusbar.setObjectName("statusbar")
        ProductWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ProductWindow)
        QtCore.QMetaObject.connectSlotsByName(ProductWindow)

    def retranslateUi(self, ProductWindow):
        _translate = QtCore.QCoreApplication.translate
        ProductWindow.setWindowTitle(_translate("ProductWindow", "ООО \"Обувь\" - Управление товарами"))
        self.order_button.setText(_translate("ProductWindow", "Заказы"))
        self.add_button.setText(_translate("ProductWindow", "Добавить товар"))
        self.search_label.setText(_translate("ProductWindow", "Поиск"))
        self.sort_label.setText(_translate("ProductWindow", "Сортировка"))
        self.user_label.setText(_translate("ProductWindow", "ФИО Пользователя"))
        self.logout_button.setText(_translate("ProductWindow", "Выход"))
